#!/bin/sh

strpos() {
    local x=${1%%$2*}
    [ "$x" = "$1" ] && echo -1 || echo "${#x}"
}

cutstr() {
    echo "$1" | cut -c$2-$3
}

chstr() {
    local x=$(strpos "$1" "$2")
    [ $x -eq -1 ] && echo "$1" || echo "$(cutstr "$1" 1 $x)$3$(cutstr "$1" $(($x+$(expr length $2)+1)))"
}

chstr "$@"
